### ISSUE TITLE
Mimweb is not responding to requests during delay

### ISSUE THREAD

**Issue by github-not-allow-me-to-delete-profile** [KevCui/mitm-scripts#2]
I use web version of mimproxy so I run it like this:
`mitmweb --listen-port 8866 -s mitm-delay-request.py `

I configured `delay-request.yaml` it works perfectly. I setup quite long delay time 50s and sometime even couple of minutes.

 But  as `delay` in `utils.py` file use `sleep` function and stop whole process. And it impossible to open other response while it sleeps.

Maybe someone have any idea how overcome this, or maybe using not sleep, but something else 

I've attached screenshot where you can see delay is significant (35 seconds) to open previous response, which already executed. So mitmweb not responding during this delay.

![mitmweb](https://user-images.githubusercontent.com/7569043/117176603-55d8b380-add0-11eb-8f0b-8a74ff27539f.png)

**Comment by github-not-allow-me-to-delete-profile** [comment]
I tried adopt this example https://gist.github.com/jokester/0a1cc9656e42120429089207b4f33846

But in this case: `Response content missing.` so I can't see any responses

**Comment by KevCui** [comment]
Hi @Saatsazov, the latest commit should fix the issue you reported. Please give it a try :point_up:

**Comment by github-not-allow-me-to-delete-profile** [comment]
Hello @KevCui,

It's working like a charm now. Thank you.
